Change health check URL in GitHub Actions workflow

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -57,7 +57,7 @@ jobs:
           npm start & sleep 10
 
           echo "Checking if the server is running..."
-          curl --fail 'http://localhost:8000/api/question/getQuestion?order=newest&search=' || (echo "Server failed to start" && killall node && exit 1)
+          curl --fail 'http://localhost:8000/api/docs' || (echo "Server failed to start" && killall node && exit 1)
 
           echo "Server started successfully. Now stopping..."
           killall node
